# Nome da sua GitHub Action
name: Generate Contribution Animation

# Define quando a Action será executada
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

# Tarefas que a Action vai executar
jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      # Pega o código do seu repositório
      - uses: actions/checkout@v3

      # GERA A ANIMAÇÃO DO PAC-MAN (aqui está a mudança)
      - name: Generate Pac-Man Animation
        uses: anzhihe/anzhihe-contributions-action@v1
        with:
          # Seu nome de usuário do GitHub (pega automaticamente)
          user: ${{ github.repository_owner }}
          # O diretório de saída (para manter a pasta dist)
          output_dir: dist
          # O nome do novo arquivo de animação
          file_name: contribution-pacman.svg

      # Faz o push da nova animação para o repositório
      - name: Push pacman animation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: generate pacman animation"
          branch: main
          file_pattern: dist/contribution-pacman.svg
