# Nome da GitHub Action
name: Generate Snake Animation

# Define quando a Action será executada
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

# Tarefas que a Action vai executar
jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      # Pega o código do seu repositório
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # AQUI ESTÁ A CORREÇÃO: Pede para gerar OS DOIS arquivos
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Faz o push dos arquivos gerados para o repositório
      - name: Push generated files to the repo
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
